app = angular.module("app", [
  "ngRoute"
  "ngResource"
  "ui.bootstrap"
  "about"
  "contact"
  "services"
  "resume"
  "check"
  "helloWorld"
  "scottisms"
  "email"
  "visitors"
  "sort"
  "ip"
])

# templateCahce in _public/templates.js file (generated by gulp)

app.config(["$routeProvider", ($routeProvider) ->
  $routeProvider.when("/about", {
      templateUrl: "about/about.html"
      controller: "aboutController"
    }).when("/services", {
      templateUrl: "web-services/services.html"
      controller: "servicesController"
    }).when("/resume", {
      templateUrl: "resume/resume.html"
      controller: "resumeController"
    }).when("/contact", {
      templateUrl: "contact/contact.html"
      controller: "contactController"
    }).otherwise({
      redirectTo: "/about"
    })
])

app.config(["$httpProvider", ($httpProvider) ->
  # Nothing right now
])

app.constant('apiPrefix', 'http://50.132.25.179:8080')
#app.constant('apiPrefix', 'http://127.0.0.1:8080')

app.controller("appController", ($scope, ipService) ->
  # Shout-out to my fiance
  $scope.pageTitle = "Hi Katie!"

  $.getJSON("http://jsonip.com?callback=?", (data) ->
    ipService.post(data.ip)
  )
)